import { Inter } from "next/font/google";
import "~/styles/globals.css";
import { Navbar } from "../components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main className="flex min-h-screen flex-col">
          <Navbar />
          <div className="mx-auto flex w-full max-w-5xl px-4 py-6">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
